### ISSUE TITLE
Clarify how to override default values

### ISSUE THREAD

**Issue by jsalvata** [lorenzoaiello/terraform-aws-rds-alarms#1]
The README file says:

> Alarms Always Created (**default values can be overridden**):
> 
> CPU Utilization above 90%
> Disk queue depth above 64
> Disk space less than 10 GB
> EBS Volume burst balance less than 100
> Freeable memory below 256 MB
> Swap usage above 256 MB
> Anomalous connection count

But the terraform documentation does not provide any hints on how to override values in resources defined by sub-modules. How are these default values overriden?

**Comment by lorenzoaiello** [comment]
Thanks for catching and resolving that. Can I consider this issue closed now?

**Comment by jsalvata** [comment]
Yes, thanks!
