### ISSUE TITLE
Support / Maintenance of this module...?

### ISSUE THREAD

**Issue by AndrewFarley** [lorenzoaiello/terraform-aws-rds-alarms#14]
Hey, I/we avidly use this module in some foundational components and would like to offer to maintain this module moving forwards @lorenzoaiello if you're keen.  It looks like you don't hardly get a chance to review/merge/update/support this repo.  So we'd be happy to take this on.  Would you mind?  Please reach out to me on my email on my profile to discuss further.

And yes, I realize I could fork this but I think for the folks that have forked/starred/used this repo it would be good for them to transparently-ish be able to continue using this module without  manually changing to an fork.  Would be happy to transfer ownership to us to our org https://github.com/DevOps-Nirvana/ and add you as an fellow manager of this repo, or to simply add us as a contributor and give us the ability to do releases (eg: setup some Github Actions to do this automatically upon release).

Thoughts?

**Comment by AndrewFarley** [comment]
To show some "confidence" and desire to take this on, I've pushed two PRs closing two of the three pending issues.  When I've a little more time I'll make a third PR as well for the last one.

**Comment by AndrewFarley** [comment]
@lorenzoaiello Ping pong, you still around?

**Comment by lorenzoaiello** [comment]
@AndrewFarley DM'ed
