### ISSUE TITLE
wrong variable description and example

### ISSUE THREAD

**Issue by Krad-dono** [lorenzoaiello/terraform-aws-rds-alarms#21]
So I used this module to provision database alarms as per example. It did not work - all alarms were stuck in **Insufficient data** state. I did raise a case to AWS support so they looked at my alarms and identified that **database ID** was used where **Identifier** need to be used. This is for RDS SQL Server at least.
Your example says:
`db_instance_id = aws_db_instance.default.id`
Should be:
`db_instance_id = aws_db_instance.default.identifier`
Please amend documentation accordingly.

**Comment by dudeitssm** [comment]
To add some more context, and to help out newbie Terraform users puzzled by this issue, here's what that means...

Example: I have a single node RDS cluster, `example-rds` with a writer node.
The _correct_ value that has to be substituted within the `db_instance_id =` input would be `db_instance_id = example-db-1` and **not** `example-db`.

I've also attached a screenshot to show what that means.

The green checkmark is the value you want substituted.
The red cross is what's currently happening in the repo provided example.

![example](https://github.com/lorenzoaiello/terraform-aws-rds-alarms/assets/36095297/31e9e016-38d8-46dc-8f3b-f8d79e1e31c2)
