### ISSUE TITLE
Feature Request/Interest: Disable certain types checks

### ISSUE THREAD

**Issue by jbarno** [lorenzoaiello/terraform-aws-rds-alarms#7]
I'm wondering if there's anybody else out there whose using this module and wished they could configure only a subset of these alarms. Perhaps passing an `enabled = False` boolean in for the various types of checks. Loosely I think it could be:

- cpu 
- disk 
- memory 
- anomaly

These can then be used in the aws_cloudwatch_metric_alarm resources as the cpu_credit resource does for the count parameter.

As of right now I just define variables such that the alarm won't actually ever alarm, which isn't ideal. I'd be willing to fork and give this a try if there's interest. Or if there's another way to accomplish this please enlighten me.

**Comment by AndrewFarley** [comment]
Implemented in #13
